export const RESET_ACTIVE_GAME = 'RESET_ACTIVE_GAME';

export const FETCH_ALL_GAMES_IN_DB_REQUESTED = 'FETCH_ALL_GAMES_IN_DB_REQUESTED';
export const FETCH_ALL_GAMES_IN_DB_SUCCEEDED = 'FETCH_ALL_GAMES_IN_DB_SUCCEEDED';
export const FETCH_ALL_GAMES_IN_DB_FAILED = 'FETCH_ALL_GAMES_IN_DB_FAILED';

export const FIND_POPULAR_GAMES_REQUESTED = 'FIND_POPULAR_GAMES_REQUESTED';
export const FIND_POPULAR_GAMES_SUCCEEDED = 'FIND_POPULAR_GAMES_SUCCEEDED';
export const FIND_POPULAR_GAMES_FAILED = 'FIND_POPULAR_GAMES_FAILED';

export const SEARCH_BY_TITLE_REQUESTED = 'SEARCH_BY_TITLE_REQUESTED';
export const SEARCH_BY_TITLE_SUCCEEDED = 'SEARCH_BY_TITLE_SUCCEEDED';
export const SEARCH_BY_TITLE_FAILED = 'SEARCH_BY_TITLE_FAILED';